### ISSUE TITLE
Will not work with Ubuntu 24.04

### ISSUE THREAD

**Issue by tresf** [microsoft/ProcMon-for-Linux#124]
Followed steps here:
* https://github.com/microsoft/ProcMon-for-Linux/blob/main/INSTALL.md

Error:

```
owner@ubuntu-2404:~$ procmon 
procmon: error while loading shared libraries: libsysinternalsEBPF.so: cannot open shared object file: No such file or directory
```

Attempt to reinstall sysinternalsebpf throws an error:
```diff
  owner@ubuntu-2404:~$ sudo apt-get install --reinstall sysinternalsebpf 
  Reading package lists... Done
  Building dependency tree... Done
  Reading state information... Done
  0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 70 not upgraded.
  Need to get 0 B/705 kB of archives.
  After this operation, 0 B of additional disk space will be used.
  (Reading database ... 248301 files and directories currently installed.)
  Preparing to unpack .../sysinternalsebpf_1.4.0_amd64.deb ...
- /var/lib/dpkg/info/sysinternalsebpf.prerm: 4: [: upgrade: unexpected operator
  Unpacking sysinternalsebpf (1.4.0) over (1.4.0) ...
  Setting up sysinternalsebpf (1.4.0) ...
  Cannot create sysinternalsEBPF directory
  Make sure you are root or sudo
  Processing triggers for man-db (2.12.0-4build2) ...
  Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
```

Workaround:

~~None.  I tried to compile from source, but the instructions are for older clang, the bcc dependency had too many compilation errors.   Installing from repo got further, but couldn't find a way to resolve `sysinternalsEBPF_common.h`, so I gave up.~~

Workaround here: https://github.com/microsoft/ProcMon-for-Linux/issues/124#issuecomment-2616861900

**Comment by tresf** [comment]
Ok, found a workaround:

```bash
sudo mkdir -p /opt/sysinternalsEBPF && sudo /usr/bin/libsysinternalsEBPFinstaller -i
```

It appears there's something wrong with the sysinternalsEBPF install.  This is what it says if I try without the directory created:

```bash
owner@ubuntu-2404:~$ sudo /usr/bin/libsysinternalsEBPFinstaller -i
# Cannot create sysinternalsEBPF directory
# Make sure you are root or sudo
```

**Comment by tresf** [comment]
Hmm... https://github.com/microsoft/SysinternalsEBPF/blob/main/INSTALL.md doesn't mention Ubuntu 24.04 as being supported, so I guess this is a bug with SysinternalsEBPF, not here, right?

**Comment by MarioHewardt** [comment]
Hi - thanks for reporting this issue. Yes, this definately seems like an issue with SysinternalsEBPF. The error during uninstall/remove is a bug that I have a fix for but I still need to investigate the directory creation error. With your workaround, does Procmon run?

**Comment by tresf** [comment]
> Hi - thanks for reporting this issue. Yes, this definately seems like an issue with SysinternalsEBPF. The error during uninstall/remove is a bug that I have a fix for but I still need to investigate the directory creation error. With your workaround, does Procmon run?

Yes, `procmon` works great with the workaround.  It wasn't obvious initially that `libsysinternalsEBPF.so` is it's own self-installer, so this missing on the system seemed like a failed install step.  Before giving up, I read the help on `libsysinternalsEBPFinstaller` and quickly realized it's a self-extracting tool and created the directory to see if it'd get further.

**Comment by tresf** [comment]
Sadly, I cannot reproduce the original issue either... 

```bash
sudo rm -rf /opt/sysinternalsEBPF/
sudo /usr/bin/libsysinternalsEBPFinstaller -i
# Success!
# Library installed to	/usr/lib/x86_64-linux-gnu/libsysinternalsEBPF.so
# Header installed to	/usr/include/libsysinternalsEBPF.h
# Support files installed to /opt/sysinternalsEBPF
```

... so I'm not actually certain what the original issue was caused by. :/

**Comment by MarioHewardt** [comment]
I tried it as well on 24.04 and it seemed to work:

`
~/SysinternalsEBPF/build/deb$ sudo /usr/bin/libsysinternalsEBPFinstaller -i
Success!
Library installed to    /usr/lib/x86_64-linux-gnu/libsysinternalsEBPF.so
Header installed to     /usr/include/libsysinternalsEBPF.h
Support files installed to /opt/sysinternalsEBPF
`
These are the permissions it requests when creating the directory:

mode_t dirMode = S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH;

I'll make sure to fix the sysinternalsEBPF uninstall error when we release next time (and also add the packages to 24.04). 

Thanks for all the help!

**Comment by tresf** [comment]
Thanks.  I guess this is safe to close as invalid, but I have a sneaking suspicion it'll come back.  The only app in `/opt` that I had at the time of installing was `winehq-stable`.  There's two other apps that I install to `/opt` using makeself and makself uses a very strict umask, so this may be self-inflicted.   Thanks for the quick reply!
